version: '3.3'

services:
  django:
    container_name: intro_django
    build: 
      context: .
    ports: 
      - 8000:8000
    command: |
      sh -c 'pip install -r requirements.txt && \
      python manage.py makemigrations && \
      python manage.py migrate && \
      python manage.py runserver 0.0.0.0:8000'
  